### ISSUE TITLE
feat: add docker file 

### ISSUE THREAD

**Issue by fraybabak** [fraybabak/hexagonal_example_nodejs#1]
Docker file for node 20.

**Comment by Rajdeep1311** [comment]
Which port does the application run on?

**Comment by fraybabak** [comment]
check the İndex.ts inside the file. I add port variable.

**Comment by Rajdeep1311** [comment]
@fraybabak sir I would like to request you something. Could you please write a recommendation about your experience of working with me on this issue in my LinkedIn account?
